import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Stupid simple WebAuthn',
  description: 'Generated by me in 2024 :)',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="w-full max-w-5xl items-center justify-center font-mono text-sm lg:flex">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
